name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2

  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
        - aarch64
        - x86_64
        os:
        - apple-darwin
        - unknown-linux-gnu
        - unknown-linux-musl
        include:
        - os: apple-darwin
          goos: darwin
        - os: unknown-linux-gnu
          goos: linux
        - os: unknown-linux-musl
          goos: linux
        - arch: aarch64
          goarch: arm64
        - arch: x86_64
          goarch: amd64

    needs:
    - release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - uses: jirutka/setup-alpine@v1
      with:
        branch: v3.21
        packages: >
          go
      if: matrix.os == 'unknown-linux-musl'

    - run: go build -o lfs-minio_${{ matrix.arch }}-${{ matrix.os }}
      if: matrix.os != 'unknown-linux-musl'
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}

    - run: go build -o lfs-minio_${{ matrix.arch }}-${{ matrix.os }}
      if: matrix.os == 'unknown-linux-musl'
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      shell: alpine.sh {0}

    - name: Upload binary to release
      uses: softprops/action-gh-release@v2
      with:
        files: lfs-minio_${{ matrix.arch }}-${{ matrix.os }}
